### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by leontoeides** [domodwyer/bloom2#3]
When I initialize the Bloom2 filter like so: 

```
let mut bloom_filter: Bloom2<RandomState, CompressedBitmap, MyStruct> = BloomFilterBuilder::default()
    .size(FilterSize::KeyBytes4)
    .build();
```

I receive the following error when my program is run:

```
The application panicked (crashed).
Message:  index out of bounds: the len is 16 but the index is 275465
Location: C:\Users\User Name\.cargo\registry\src\github.com-1ecc6299db9ec823\bloom2-0.2.0\src\bitmap\compressed_bitmap.rs:254
```

However, if I initialize like this:

```
let mut bloom_filter: Bloom2<RandomState, CompressedBitmap, MyStruct> = Bloom2::default();
```

It works well. Nice and fast!

If you require more detail, let me know!

**Comment by domodwyer** [comment]
Hey @leontoeides

**Thanks for reporting this!**

It was an oversight with the `BloomFilterBuilder::size()` method - it would set the key size used by the filter but not expand the underlying bitmap size. This has been fixed in 1105e7a by resizing the underlying bitmap when using the `CompressedBitmap` implementation :)

Again, thanks for reporting this, it's really appreciated and I am truly pleased you have found the crate useful! 👍 

Dom

**Comment by domodwyer** [comment]
I have pushed v0.2.1 containing this fix to crates.io 👍

**Comment by leontoeides** [comment]
That was fast! Thank you so much
